USE mademoiselle_borges;

CREATE ROLE admin;
CREATE USER hen; -- Henrique Borges
CREATE USER mii; -- MARIA IVANOVNA IVANOVA

CREATE ROLE p_admin;
CREATE USER hom; -- Herr Otto Mustermann

CREATE ROLE employee;
CREATE USER CLEAN00001;
CREATE USER SALES00001;
CREATE USER SECUR00001;
CREATE USER MARKT00001;
CREATE USER PUBLC00001;
CREATE USER ENTMT00001;


CREATE ROLE guest;
CREATE USER guest; -- global
